---
title: "research"
author: "Eran Aizikovich and Yuval Segal"
date: "6/14/2022"
output: html_document
---


```{r load-packages, include = FALSE}
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(dplyr)

library("ggalluvial")
library("gridExtra") 



library(tidymodels)
library(schrute)
library(lubridate)
```

```{r include = FALSE}
# opts_chunk$set(echo=FALSE) # hide source code in the document
path <- setwd("..")
df <- read.csv(
  "data\\data_no_red.csv")
glimpse(df)
```

```{r}
g1 <- ggplot(df, aes(x=annotator_severity))+
        geom_density(fill = 'dark red', alpha =0.3) +
        
        labs(title = "Annotator Severity")+  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

g2 <-  ggplot(df, aes(x=hate_speech_score))+
        geom_density(fill = 'dark red', alpha =0.3) +
        
        labs(title = "Hate Speech Score")+
                  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

g3 <-  ggplot(df, aes(x=hypothesis))+
        geom_density(fill = 'dark red', alpha =0.3) +
        
        labs(title = "Hypothesis")+
                  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

g4 <-  ggplot(df, aes(x=std_err))+
        geom_density(fill = 'dark red', alpha =0.3) +
        
        labs(title = "STD error")+
                  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

grid.arrange(g1,g2,g3, g4,ncol=2)

```


שים לב הגרפים פה למטה לא מדויקים. אתה בודק מדד שהוא קבוע פר פוסט על כל הרשומות ולא רק על טבלה המכילה שורה אחת לכל פוסט
```{r}

g1 <- ggplot(df, aes(x=insult))+
        geom_bar(fill = 'dark green', alpha =0.3) +
        
        labs(title = "Insult")+  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

g2 <-  ggplot(df, aes(x=humiliate))+
        geom_bar(fill = 'dark green', alpha =0.3) +
        
        labs(title = "Humiliate")+
                  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

g3 <-  ggplot(df, aes(x=dehumanize))+
        geom_bar(fill = 'dark green', alpha =0.3) +
        
        labs(title = "Dehumanize")+
                  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

g4 <-  ggplot(df, aes(x=violence))+
        geom_bar(fill = 'dark green', alpha =0.3) +
        
        labs(title = "violence")+
                  
        
        theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
              axis.line = element_line( colour = "black")
        )

grid.arrange(g1,g2,g3, g4,ncol=2)

```

# התחלנו
```{r}
df <- df %>% filter(!(hatespeech==1))
```

```{r}
# dput(names(df))

df <- df[,c("comment_id", "annotator_id", "sentiment", "respect", "insult", 
"humiliate", "dehumanize", "violence", "genocide", "attack_defend", 
"hatespeech", "hate_speech_score", "std_err", "target_race", "target_religion", "target_gender", "target_sexuality", 
"annotator_gender", "annotator_educ", "annotator_income", "annotator_ideology", 
"annotator_age", "annotator_race", "annotator_religion", "annotator_sexuality"
)]
```
annotatoes and comments
```{r}
col_an <- c("annotator_id", "annotator_gender", "annotator_educ", "annotator_income", "annotator_ideology", "annotator_age", "annotator_race", "annotator_religion", "annotator_sexuality")
df_an <-  distinct(df, annotator_id, .keep_all = TRUE)[, col_an]
df_an

```
```{r}
col_com <- c("comment_id", "sentiment", "respect", "insult", 
"humiliate", "dehumanize", "violence", "genocide", "attack_defend", 
"hatespeech", "hate_speech_score", "target_race", "target_religion", "target_gender", "target_sexuality")
df_com <-  distinct(df, comment_id, .keep_all = TRUE)[,col_com]
df_com 
```


```{r}
df2<-df[!(df$annotator_race==0 | df$annotator_race=="pacific_islander"),]
table(df2$annotator_race)

```

```{r}
#obtain stratified sample
strat_sample <- df2 %>%
                  group_by(comment_id, annotator_race) %>%
                  sample_n(size=1)
```

```{r}
# table(strat_sample$comment_id)

countn <- count(strat_sample[,'comment_id'], comment_id)
morethan <- countn %>% filter(n>3)

diverced_anno <- df2 %>% filter(comment_id %in% morethan$comment_id)

strat_comments <- diverced_anno %>%
                  group_by(comment_id, annotator_race) %>%
                  sample_n(size=1)

strat_comments <- within(strat_comments, hatespeech[hatespeech == 2] <- 1)
strat_comments
```
# Model
## split data
```{r}
set.seed(1122)

df_model <- strat_comments
df_split <- initial_split(df_model)

train <- training(df_split)
test <- testing(df_split)
```
## fit model
```{r}

model <- glm(hatespeech ~ hate_speech_score+humiliate+annotator_race , data = train, family = binomial)

summary(model)

```

