---
title: "Presentation"
author: "Eran Aizikovich"
date: "5/16/2022"
output: html_document
---

```{r setup, include=FALSE}

```

## R Markdown
The big Q: How he annotator's background effects his way of annotating? 
Lets Start, load file csv

```{r}
path <- setwd("..")
df <- read.csv(
  "data\\measuring_hate_speech.csv")
```
## Clean unrelated data

```{r}
df
```


### Race
```{r}

df_wo_red <- df                
df_wo_red['annotator_race'] <- 0
                       
df_wo_red <- within(df_wo_red, 
annotator_race[annotator_race_asian == 'True']<-'asian')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_black == 'True']<-'black')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_latinx == 'True']<-'latinx')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_middle_eastern == 'True']<-'middle_eastern')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_native_american == 'True']<-'native_american')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_pacific_islander == 'True']<-'pacific_islander')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_white == 'True']<-'white')
df_wo_red <- within(df_wo_red, annotator_race[annotator_race_other == 'True']<-'other')
# df_wo_red <- filter(df_wo_red, annotator_race != 0)



df_wo_red['target_race'] <- 0

df_wo_red <- within(df_wo_red, target_race[target_race_asian == 'True']<-'asian')
df_wo_red <- within(df_wo_red, target_race[target_race_black == 'True']<-'black')
df_wo_red <- within(df_wo_red, target_race[target_race_latinx == 'True']<-'latinx')
df_wo_red <- within(df_wo_red, target_race[target_race_middle_eastern == 'True']<-'middle_eastern')
df_wo_red <- within(df_wo_red, target_race[target_race_native_american == 'True']<-'native_american')
df_wo_red <- within(df_wo_red, target_race[target_race_pacific_islander == 'True']<-'pacific_islander')
df_wo_red <- within(df_wo_red, target_race[target_race_white == 'True']<-'white')
df_wo_red <- within(df_wo_red, target_race[target_race_other == 'True']<-'other')
# df_wo_red <- filter(df_wo_red, target_race != 0)

anno_wo_red<-df_wo_red

```

### Religion

```{r}

df_wo_red['annotator_religion'] <- 0
                       
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_atheist == 'True']<-'atheist')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_buddhist == 'True']<-'buddhist')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_christian == 'True']<-'christian')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_hindu == 'True']<-'hindu')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_jewish == 'True']<-'jewish')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_mormon == 'True']<-'mormon')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_muslim == 'True']<-'muslim')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_nothing == 'True']<-'nothing')
df_wo_red <- within(df_wo_red, annotator_religion[annotator_religion_other == 'True']<-'other')
# df_wo_red <- filter(df_wo_red, annotator_religion!=0)


df_wo_red['target_religion'] <- 0
                       
df_wo_red <- within(df_wo_red, target_religion[target_religion_atheist == 'True']<-'atheist')
df_wo_red <- within(df_wo_red, target_religion[target_religion_buddhist == 'True']<-'uddhist')
df_wo_red <- within(df_wo_red, target_religion[target_religion_hindu == 'True']<-'hindu')
df_wo_red <- within(df_wo_red, target_religion[target_religion_jewish == 'True']<-'jewish')
df_wo_red <- within(df_wo_red, target_religion[target_religion_mormon == 'True']<-'mormon')
df_wo_red <- within(df_wo_red, target_religion[target_religion_muslim == 'True']<-'muslim')
df_wo_red <- within(df_wo_red, target_religion[target_religion_other == 'True']<-'other')

# df_wo_red <- filter(df_wo_red, target_religion != 0)



```
### Sexuality

```{r}
df_wo_red['annotator_sexuality'] <- 0

df_wo_red <- within(df_wo_red, annotator_sexuality[annotator_sexuality_bisexual == 'True']<-'bisexual')
df_wo_red <- within(df_wo_red, annotator_sexuality[annotator_sexuality_gay == 'True']<-'gay')
df_wo_red <- within(df_wo_red, annotator_sexuality[annotator_sexuality_straight == 'True']<-'straight')
df_wo_red <- within(df_wo_red, annotator_sexuality[annotator_sexuality_other == 'True']<-'other')

# df_wo_red <- filter(df_wo_red, annotator_sexuality!=0)


df_wo_red['target_sexuality'] <- 0

df_wo_red <- within(df_wo_red, target_sexuality[target_sexuality_bisexual == 'True']<-'bisexual')
df_wo_red <- within(df_wo_red, target_sexuality[target_sexuality_gay == 'True']<-'gay')
df_wo_red <- within(df_wo_red, target_sexuality[target_sexuality_lesbian == 'True']<-'gay')
df_wo_red <- within(df_wo_red, target_sexuality[target_sexuality_straight == 'True']<-'straight')
df_wo_red <- within(df_wo_red, target_sexuality[target_sexuality_other == 'True']<-'other')

# df_wo_red <- filter(df_wo_red, target_sexuality != 0)
```
### Remove redundant cols
```{r}
# Annotator

 #Race
df_wo_red <- subset(df_wo_red, select = -c(annotator_race_asian, annotator_race_black, annotator_race_latinx, annotator_race_middle_eastern, annotator_race_native_american, annotator_race_pacific_islander, annotator_race_white, annotator_race_other))

 #Religion
df_wo_red <- subset(df_wo_red, select = -c(annotator_religion_atheist, annotator_religion_buddhist, annotator_religion_christian, annotator_religion_hindu, annotator_religion_jewish, annotator_religion_mormon, annotator_religion_muslim, annotator_religion_nothing, annotator_religion_other))

 #Sexuality
df_wo_red <- subset(df_wo_red, select = -c(annotator_sexuality_bisexual, annotator_sexuality_gay, annotator_sexuality_straight, annotator_sexuality_other, annotator_trans))

#Target
df_wo_red <- subset(df_wo_red, select = -c( target_race_asian, target_race_black,
target_race_latinx, target_race_middle_eastern, target_race_native_american,
target_race_pacific_islander, target_race_white, target_race_other, target_religion_atheist, target_religion_buddhist,
target_religion_christian, target_religion_hindu, target_religion_jewish,
target_religion_mormon, target_religion_muslim, target_religion_other,
target_religion, target_origin_immigrant, target_origin_migrant_worker,
target_origin_specific_country, target_origin_undocumented, target_origin_other,
target_origin, target_gender_men, target_gender_non_binary,
target_gender_transgender_men, target_gender_transgender_unspecified, target_gender_transgender_women,
target_gender_women, target_gender_other,
target_sexuality_bisexual, target_sexuality_gay, target_sexuality_lesbian,
target_sexuality_straight, target_sexuality_other,
target_age_children, target_age_teenagers, target_age_young_adults,
target_age_middle_aged, target_age_seniors, target_age_other,
target_age, target_disability_physical, target_disability_cognitive,
target_disability_neurological, target_disability_visually_impaired, target_disability_hearing_impaired,
target_disability_unspecific, target_disability_other, target_disability))

# Post
df_wo_red <- subset(df_wo_red, select = -c(text, platform, status, text))

# Redundant
df_wo_red <- subset(df_wo_red, select=-c(annotator_income_.10k,annotator_income_10k.50k, annotator_income_50k.100k, annotator_income_100k.200k,
annotator_income_.200k, annotator_ideology_extremeley_conservative,annotator_ideology_conservative,
annotator_ideology_slightly_conservative, annotator_ideology_neutral,annotator_ideology_slightly_liberal,
annotator_ideology_liberal, annotator_ideology_extremeley_liberal,annotator_ideology_no_opinion, annotator_education_some_high_school,
annotator_education_high_school_grad, annotator_education_some_college, annotator_education_college_grad_aa, annotator_education_college_grad_ba,
annotator_education_professional_degree, annotator_education_masters, annotator_education_phd, annotator_gender_men, annotator_gender_women, annotator_gender_non_binary, annotator_gender_prefer_not_to_say, annotator_gender_self_describe, annotator_transgender, annotator_cisgender, annotator_transgender_prefer_not_to_say))
```

```{r}
glimpse(df_wo_red)
```

## Exploring Or Data
```{r}
count_annot <- count(df_wo_red,annotator_id)

ggplot(count_annot, aes(x=n))+
  geom_bar(fill = 'dark red', alpha =0.3) +
  labs(
    x = "Post count",
    y = "Annotators count",
    fill = "Class",
    title = "Number of posts annotated by each individual",
    
  )+
  theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
        axis.line = element_line( colour = "black")
  )
```
```{r}
ggplot(df_wo_red, aes(x=hate_speech_score))+
  geom_density(fill = 'dark green', alpha =0.3) +
  labs(
    x = "Hate Speech Score",
    y = "Density",
    fill = "Class",
    title = "Density of posts Scores",
    
  )+
  theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
        axis.line = element_line( colour = "black")
  )
```

```{r}
race_filter <- df_wo_red %>% filter(df_wo_red['annotator_race'] != 0)

p_anno <- ggplot(race_filter, aes(x=annotator_race))+
  geom_bar(fill = 'dark red', alpha =0.3) +
  labs(
    x = "Annotator Race",
    y = "Counter",
    title = "Number of Annotators for each Race",
    subtitle ="Dark red fill for annotators",
    
    
  )+
  theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
        axis.line = element_line( colour = "black")
  )

```
```{r}
race_filter <- df_wo_red %>% filter(df_wo_red['target_race'] != 0)

p_target <- ggplot(race_filter, aes(x=target_race))+
  geom_bar(fill = 'dark blue', alpha =0.3) +
  labs(
    x = "Traget Race",
    y = "Counter",
    title = "Number of Target for each Race",
    subtitle ="Dark blue fill for targets",
  )+
  theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
        axis.line = element_line( colour = "black")
  )

```

```{r}
grid.arrange(p_anno,p_target, ncol=2)

```

```{r}
race_filter <- within(race_filter, annotator_race[annotator_race == 'middle_eastern']<-'other')
race_filter <- within(race_filter, annotator_race[annotator_race == 'pacific_islander']<-'other')
race_filter <- within(race_filter, annotator_race[annotator_race == 'native_american']<-'other')
race_filter <- within(race_filter, annotator_race[annotator_race == '0']<-'other')
count_races <- count(race_filter, target_race, annotator_race)

```


```{r}
#("red", "blue", "yellow",'green')
ggplot(count_races,
       aes( axis1 = annotator_race, axis2 = target_race, y=n)) +
    geom_alluvium(aes(fill = target_race, color = target_race), 
                  width = 4/12, alpha = 0.5, knot.pos = 0.4) +
    geom_stratum(width = 1/4,color = "grey") +
    scale_fill_manual(values  =c("red", "blue", "yellow", "purple", "cadetblue4", "#95CC5E", "lightgrey", "green")) +
    scale_color_manual(values  =c("red", "blue", "yellow", "purple", "cadetblue4", "#95CC5E", "lightgrey", "green")) +
    geom_text(stat = "stratum", aes(label = after_stat(stratum)), size=2) +
    scale_x_continuous(breaks = 1:2, labels = c("Annotators", "Target"))  +
    theme_minimal() +
    theme(
        legend.position = "left",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.text.y = element_blank(),
        axis.text.x = element_text(size = 14, face = "bold"),
        )+
    labs(
      title = "Common Distribution Between - Targets Race & Annotators Race",
      subtitle = "Colours represent the target race",
      y = 'Races'
      # color = "Target Race"
    )
```
```{r}
p1 <- ggplot(df_wo_red, aes(x=annotator_age))+
  geom_density(fill = 'dark red', alpha =0.3) +
  labs(
    x = "Age",
    y = "Density",
    
    title = "Density of annotators age",
    
  )+
  theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
        axis.line = element_line( colour = "black")
  )
p2 <-  ggplot(df_wo_red, aes(x=annotator_age))+
  geom_bar(fill = 'dark red', alpha =0.3) +
  labs(
    x = "Age ",
    y = "Counter",
    
    title = "Nunber of annotators age",
    
  )+
  theme(axis.text.x = element_text(angle = 75,vjust = 0.5),
        axis.line = element_line( colour = "black")
  )

grid.arrange(p1,p2, ncol=2)
```
```{r}
ggplot(race_filter, aes (x = hate_speech_score, fill = annotator_race))+
  geom_density(alpha =0.2)+
  labs(
    title = "Density for hate speech score", 
    subtitle = "Fill for the annotator race", 
    x= "hate speech score", 
    y = "density",
    fill = "Annotator Race")+
  theme_minimal()
```
```{r}

```



```{r}
white_anno <-  filter(race_filter, annotator_race == "white"&target_race != "other"&target_race != "pacific_islander"&target_race != "native_american"&target_race != "middle_eastern")

black_anno <- race_filter %>% filter(annotator_race == 'black'&target_race != "other"&target_race != "pacific_islander"&target_race != "native_american"&target_race != "middle_eastern")

asian_anno <- race_filter %>% filter(annotator_race == 'asian'&target_race != "other"&target_race != "pacific_islander"&target_race != "native_american"&target_race != "middle_eastern")

latin_anno <- race_filter %>% filter(annotator_race == 'latinx'&target_race != "other"&target_race != "pacific_islander"&target_race != "native_american"&target_race != "middle_eastern")


plot_w <- ggplot(white_anno, aes (x = hate_speech_score, fill = target_race))+
  geom_density(alpha =0.2)+
   scale_fill_manual(values=c("red", "blue", "yellow",'green'))+
  labs(
    title = "Density for score by white annotator", 
    subtitle = "Fill for the target's race", 
    x= "Hate Speech Score", 
    y = "Density",
    fill = "Traget")+
  theme_minimal()


plot_b <- ggplot(black_anno, aes (x = hate_speech_score, fill = target_race))+
  geom_density(alpha =0.2)+
   scale_fill_manual(values=c("red", "blue", "yellow",'green'))+
  labs(
    title = "Density for score by black annotator", 
    subtitle = "Fill for the target's race", 
    x= "Hate Speech Score", 
    y = "Density",
    fill = "Traget")+
  theme_minimal()

plot_a <- ggplot(asian_anno, aes (x = hate_speech_score, fill = target_race))+
  geom_density(alpha =0.2)+
   scale_fill_manual(values=c("red", "blue", "yellow",'green'))+
  labs(
    title = "Density for score by asian annotator", 
    subtitle = "Fill for the target's race", 
    x= "Hate Speech Score", 
    y = "Density",
    fill = "Traget")+
  theme_minimal()

plot_l <- ggplot(latin_anno, aes (x = hate_speech_score, fill = target_race))+
  geom_density(alpha =0.2)+
   scale_fill_manual(values=c("red", "blue", "yellow",'green'))+
  labs(
    title = "Density for score by latin annotator", 
    subtitle = "Fill for the target's race", 
    x= "Hate Speech Score", 
    y = "Density",
    fill = "Traget")+
  theme_minimal()

```
```{r}
grid.arrange(plot_w, plot_b, plot_a, plot_l, ncol=2)

```





