---
title: "Final Report"
author: "Team Y"
date: "6/17/2022"
output: html_document
---

```{r load-packages, include = FALSE}
library(knitr)
library(tidyverse)
library(broom)
library(htmltools)
library(dplyr)
library("ggalluvial")
library("gridExtra") 
library(tidymodels)
library(schrute)
library(lubridate)
```

```{r}
# opts_chunk$set(echo=FALSE) # hide source code in the document
path <- setwd("..")
df <- read.csv(
  "data\\data_no_red.csv")

df <- df[,c("comment_id", "annotator_id", "sentiment", "respect", "insult", 
"humiliate", "dehumanize", "violence", "genocide", "attack_defend", 
"hatespeech", "hate_speech_score", "std_err", "target_race", "target_religion", "target_gender", "target_sexuality", 
"annotator_gender", "annotator_educ", "annotator_income", "annotator_ideology", 
"annotator_age", "annotator_race", "annotator_religion", "annotator_sexuality"
)]
```
# section 1 - Intro

```{r}

target_race_me <- df %>% filter(!(hatespeech==1) & annotator_race == "white")
target_race_me <- within(target_race_me, hatespeech[hatespeech == 2] <- 1)

set.seed(1122)

df_model <- target_race_me
df_model <- subset(target_race_me, select = -c(annotator_race, comment_id, annotator_id ))


df_split <- initial_split(df_model)

train <- training(df_split)
test <- testing(df_split)

model <- glm(hatespeech ~ target_race+target_religion+target_gender+target_sexuality+annotator_age, data = train)

summary(model)
```

```{r}
library(caret)

x <- predict(model, newdata = test, type = "response")
xx <- ifelse(x < 0.5, 0, 1)

xxx <- data.frame(Predicted = xx, Actual = test$hatespeech)
xxx$Predicted <- as.factor(xxx$Predicted)

xxx$Actual <- as.factor(xxx$Actual)

caret::confusionMatrix(xxx$Predicted, xxx$Actual)

```

#General
```{r}
target_race_me <- df %>% filter(!(hatespeech==1))
target_race_me <- within(target_race_me, hatespeech[hatespeech == 2] <- 1)

set.seed(1122)

df_model <- target_race_me
df_model <- subset(target_race_me, select = -c(annotator_educ, comment_id, annotator_id, hate_speech_score,sentiment,respect,insult,humiliate,dehumanize,violence,genocide,attack_defend ))


df_split <- initial_split(df_model)

train <- training(df_split)
test <- testing(df_split)

model <- glm(hatespeech ~ target_race+target_religion+target_gender+target_sexuality, data = train)
summary(model)


print("General")
x <- predict(model, newdata = test, type = "response")
xx <- ifelse(x < 0.5, 0, 1)

xxx <- data.frame(Predicted = xx, Actual = test$hatespeech)
xxx$Predicted <- as.factor(xxx$Predicted)

xxx$Actual <- as.factor(xxx$Actual)

caret::confusionMatrix(xxx$Predicted, xxx$Actual)

```
# muslim
```{r}

target_race_me <- df %>% filter(!(hatespeech==1) & annotator_religion == "atheist")
target_race_me <- within(target_race_me, hatespeech[hatespeech == 2] <- 1)

set.seed(14465)

df_model <- target_race_me
df_model <- subset(target_race_me, select = -c(annotator_race, comment_id, annotator_id ))


df_split <- initial_split(df_model)

train <- training(df_split)
test <- testing(df_split)

model <- glm(hatespeech ~ target_race+target_religion+target_gender+target_sexuality, data = train)

summary(model)

x <- predict(model, newdata = test, type = "response")
xx <- ifelse(x < 0.5, 0, 1)

xxx <- data.frame(Predicted = xx, Actual = test$hatespeech)
xxx$Predicted <- as.factor(xxx$Predicted)

xxx$Actual <- as.factor(xxx$Actual)

caret::confusionMatrix(xxx$Predicted, xxx$Actual)
```
# ATU
```{r}
target_race_me <- df %>% filter(!(hatespeech==1) & annotator_religion == "muslim")
target_race_me <- within(target_race_me, hatespeech[hatespeech == 2] <- 1)

set.seed(14253)

df_model <- target_race_me
df_model <- subset(target_race_me, select = -c( comment_id, annotator_id ))


df_split <- initial_split(df_model)

train <- training(df_split)
test <- testing(df_split)

model <- glm(hatespeech ~ target_race+target_religion+target_gender+target_sexuality, data = train)

summary(model)

x <- predict(model, newdata = test, type = "response")
xx <- ifelse(x < 0.5, 0, 1)

xxx <- data.frame(Predicted = xx, Actual = test$hatespeech)
xxx$Predicted <- as.factor(xxx$Predicted)

xxx$Actual <- as.factor(xxx$Actual)

caret::confusionMatrix(xxx$Predicted, xxx$Actual)

```

# professional_degree

```{r}


target_race_me <- df %>% filter(!(hatespeech==1) & annotator_educ == "professioAnal_degree")
target_race_me <- within(target_race_me, hatespeech[hatespeech == 2] <- 1)

set.seed(1126)

df_model <- target_race_me
df_model <- subset(target_race_me, select = -c(annotator_educ, comment_id, annotator_id, hate_speech_score,sentiment,respect,insult,humiliate,dehumanize,violence,genocide,attack_defend ))


df_split <- initial_split(df_model)

train <- training(df_split)
test <- testing(df_split)

model <- glm(hatespeech ~ target_race+target_religion+target_gender+target_sexuality, data = train)

summary(model)

x <- predict(model, newdata = test, type = "response")
xx <- ifelse(x < 0.5, 0, 1)

xxx <- data.frame(Predicted = xx, Actual = test$hatespeech)
xxx$Predicted <- as.factor(xxx$Predicted)

xxx$Actual <- as.factor(xxx$Actual)

caret::confusionMatrix(xxx$Predicted, xxx$Actual)

```

# plot confusionMatrix
          Reference
Prediction   0   1
         0 178  60
         1  53  71
```{r}

Prediction <- factor(c(0, 0, 1, 1))
Reference <- factor(c(0, 1, 0, 1))

g_i <- c(17249, 6778, 2912, 4702)
general <- c(17249/sum(g_i), 6778/sum(g_i), 2912/sum(g_i), 4702/sum(g_i))

m_i <- c(131, 40, 20, 27)
muslim <- c(131/sum(m_i), 40/sum(m_i), 20/sum(m_i), 27/sum(m_i))

p_i <- c(399,151,66,96)
pro <- c(p_i[1]/sum(p_i), p_i[2]/sum(p_i), p_i[3]/sum(p_i), p_i[4]/sum(p_i))

p_i <- c(178,60,53,71)
phd <- c(p_i[1]/sum(p_i), p_i[2]/sum(p_i), p_i[3]/sum(p_i), p_i[4]/sum(p_i))

p_i <- c(2326,829,340,604)
inc <- c(p_i[1]/sum(p_i), p_i[2]/sum(p_i), p_i[3]/sum(p_i), p_i[4]/sum(p_i)) 
  
  
g_df <- data.frame(Reference, Prediction, general)
m_df <- data.frame(Reference, Prediction, muslim)
p_df <- data.frame(Reference, Prediction, pro)
h_df <- data.frame(Reference, Prediction, phd)
i_df <- data.frame(Reference, Prediction, inc)

p1<-ggplot(data =  g_df, mapping = aes(x = Reference, y = Prediction)) +
      geom_tile(aes(fill = general), colour = "black", alpha=0.5) +
      geom_text(aes(label = sprintf("%0.3f", general)), vjust = 1, size=10) +
      scale_fill_gradient(low = "light blue", high = "dark blue") +
      labs(title = 'Confusion Matrix Ratio - General model', subtitle = " Accuracy : 0.6938 ")+
      theme_bw() + theme(legend.position = "none",
                           plot.title = element_text(hjust = 0.5, size= 20,face="bold"),
                           plot.subtitle = element_text(hjust = 0.5, size= 15))

p2<-ggplot(data =  g_df, mapping = aes(x = Reference, y = Prediction)) +
      geom_tile(aes(fill = muslim), colour = "black", alpha=0.5) +
      geom_text(aes(label = sprintf("%0.3f", muslim)), vjust = 1, size=10) +
      scale_fill_gradient(low = "light blue", high = "dark blue") +
      labs(title = 'Confusion Matrix Ratio - Muslim Annotators', subtitle = "Accuracy : 0.7248 ")+
      theme_bw()+ theme(legend.position = "none",
                           plot.title = element_text(hjust = 0.5, size= 20,face="bold"),
                           plot.subtitle = element_text(hjust = 0.5, size= 15))

p3 <- ggplot(data =  p_df, mapping = aes(x = Reference, y = Prediction)) +
        geom_tile(aes(fill = pro), colour = "black", alpha=0.5) +
        geom_text(aes(label = sprintf("%0.3f", pro)), vjust = 1, size=10) +
        scale_fill_gradient(low = "light blue", high = "dark blue") +
        labs(title = 'Confusion Matrix Ratio - Professional Degree Annotators', subtitle = " Accuracy : 0.6952 ")+
        theme_bw() + theme(legend.position = "none",
                           plot.title = element_text(hjust = 0.5, size= 18,face="bold"),
                           plot.subtitle = element_text(hjust = 0.5, size= 15),
                           axis.title=element_text(size=14))


p4 <- ggplot(data =  h_df, mapping = aes(x = Reference, y = Prediction)) +
        geom_tile(aes(fill = phd), colour = "black", alpha=0.5) +
        geom_text(aes(label = sprintf("%0.3f", phd)), vjust = 1, size=10) +
        scale_fill_gradient(low = "light blue", high = "dark blue") +
        labs(title = 'Confusion Matrix Ratio - Phd Annotators', subtitle = " Accuracy : 0.6878 ")+
        theme_bw() + theme(legend.position = "none",
                           plot.title = element_text(hjust = 0.5, size= 20,face="bold"),
                           plot.subtitle = element_text(hjust = 0.5, size= 15),
                           axis.title=element_text(size=14))

p5 <-  ggplot(data =  i_df, mapping = aes(x = Reference, y = Prediction)) +
        geom_tile(aes(fill = inc), colour = "black", alpha=0.5) +
        geom_text(aes(label = sprintf("%0.3f", inc)), vjust = 1, size=10) +
        scale_fill_gradient(low = "light blue", high = "dark blue") +
        labs(title = 'Confusion Matrix Ratio - \n100k-200k Yearly Income Annotators', subtitle = " Accuracy : 0.7148 ")+
        theme_bw() + theme(legend.position = "none",
                           plot.title = element_text(hjust = 0.5, size= 18,face="bold"),
                           plot.subtitle = element_text(hjust = 0.5, size= 15),
                           axis.title=element_text(size=14))
p1
p2
p3
p4
p5
```

```{r}
p1
p2
p3
```

